services:
  gin-server:
    container_name: gin-server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go","run","cmd/main.go"]
    ports:
      - "8080:8080"
    env_file:
      - .env
